version: "3.3"

# ======================================================================================================================
# SERVICES
# ======================================================================================================================

services:

    # --------------------------------------------------------------------------------
    # WEB SERVER
    # --------------------------------------------------------------------------------

    webserver:
      image: nginx:alpine
      working_dir: /application
      restart: always
      volumes:
          - ./app:/application
          - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      ports:
       - "${NGINX_HTTP_PORT}:80"

    php-fpm:
      image: phpdockerio/php-hi
      build: phpdocker/php-fpm
      working_dir: /application
      volumes:
        - ./app:/application
        - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/${PHP_VERSION}/fpm/conf.d/99-overrides.ini'

